### ISSUE TITLE
Stage pages: Build error on the server

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-general#185]
Notes from @brentajones 

> I think the command that runs on the server doesn't generate all the correct files, and so it fails and restarts. Then it doesn't generate the correct files again, and so on. Part of it also clears out the build folder.
> But if I also run grunt manually on the server, it does generate the correct files. If I happen to time it so that grunt generates the correct files in between the other command clearing the folder out and trying to build pages based on those, it works.
> The server command wasn't running the correct tasks in the right order. It's working for now but I want to look into it further.

**Comment by brentajones** [comment]
Closed with 2cc54db and documentation.
