### ISSUE TITLE
New England states without censusID and unemployment data

### ISSUE THREAD

**Issue by abidishajia** [nprapps/elections24-general#198]
There are a couple of New England states that don't have a `censusID` and some that don't have the unemployment data:

First is the censusID and the second is the fips
25-005-02690 25005
25-009-37995 25009
25-005-02690 25005
25-009-37995 25009
undefined 23021
undefined 23025
undefined 23019
undefined 23003
undefined 23007
undefined 23003
undefined 23007
undefined 23025
undefined 23019
undefined 23003
undefined 23003
undefined 23025
undefined 23019
undefined 23021
undefined 23021
23-019-38005 23019
23-019-39475 23019
undefined 23017
undefined 23003
undefined 23017
undefined 23013
undefined 23015
undefined 23003
undefined 23003
undefined 23029
undefined 23025
undefined 23007
undefined 23003
undefined 23007
undefined 23019
undefined 23003
undefined 23025
undefined 23003
undefined 23013
undefined 23003
23-019-73600 23019
undefined 23025
23-027-78255 23027
undefined 23019
undefined 23025
23-015-84140 23015
undefined 23003
undefined 23029
undefined 23021
undefined 23025
undefined 23019
undefined 23003
undefined 23007
undefined 23003
undefined 23007
undefined 23025
undefined 23019
undefined 23003
undefined 23003
undefined 23025
undefined 23019
undefined 23021
undefined 23021
23-019-38005 23019
23-019-39475 23019
undefined 23017
undefined 23003
undefined 23017
undefined 23013
undefined 23015
undefined 23003
undefined 23003
undefined 23029
undefined 23025
undefined 23007
undefined 23003
undefined 23007
undefined 23019
undefined 23003
undefined 23025
undefined 23003
undefined 23013
undefined 23003
23-019-73600 23019
undefined 23025
23-027-78255 23027
undefined 23019
undefined 23025
23-015-84140 23015
undefined 23003
undefined 23029
undefined 23013
undefined 23015
undefined 23013
23-015-84140 23015
undefined 23021
undefined 23025
undefined 23019
undefined 23003
undefined 23007
undefined 23003
undefined 23007
undefined 23025
undefined 23019
undefined 23003
undefined 23003
undefined 23025
undefined 23019
undefined 23021
undefined 23021
23-019-38005 23019
23-019-39475 23019
undefined 23017
undefined 23003
undefined 23017
undefined 23003
undefined 23003
undefined 23029
undefined 23025
undefined 23007
undefined 23003
undefined 23007
undefined 23019
undefined 23003
undefined 23025
undefined 23003
undefined 23003
23-019-73600 23019
undefined 23025
23-027-78255 23027
undefined 23019
undefined 23025
undefined 23003
undefined 23029
undefined 33007
undefined 33007
50-007-24400 50007
50-007-24400 50007
50-007-24400 50007

**Comment by alykat** [comment]
addressed in 4e8e830d49fbf2fa30505d53b3de9cff6184be61
