### ISSUE TITLE
Tab component: Only write to local storage if users have consented via OneTrust

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-general#279]
Might be simplest to delete it

**Comment by DanielJWood** [comment]
truth be told i don't really understand what the tab component does so i'm hesitant to make this into a pull request but i commented out those references: 
https://github.com/nprapps/elections24-general/blob/279-local-storage/src/js/components/tabs/index.js

**Comment by alykat** [comment]
done in 82a52c15625f7e227c359fc83151f483e0e0718e
