### ISSUE TITLE
County table, leader not highlighting in some cases

### ISSUE THREAD

**Issue by brentajones** [nprapps/elections24-general#322]
![Screenshot 2024-11-05 at 6 40 06 PM](https://github.com/user-attachments/assets/1d376289-c781-47ad-a4f3-3f35ea97221c)

Hamilton County shows Harris with 50% and leading, but not colored in. Trump at >50% in the previous county is colored in.

May be expected behavior if the vote-share threshold is 50%.

**Comment by alykat** [comment]
addressed in 5d13f68b5e5800a0963ce2313ae6c2dd701a9ca8
