### ISSUE TITLE
County table reporting tie when there's not a tie

### ISSUE THREAD

**Issue by brentajones** [nprapps/elections24-general#325]
Maybe a rounding thing? This is in Florida.

![Screenshot 2024-11-05 at 7 44 49 PM](https://github.com/user-attachments/assets/de7757c8-d8a5-423f-b3f3-c14c365336a3)

**Comment by hilaryfung** [comment]
Also:
![image](https://github.com/user-attachments/assets/b826e10f-05f1-48ef-a175-f9201df8634d)
