### ISSUE TITLE
Resize iframe when user clicks internal links

### ISSUE THREAD

**Issue by hilaryfung** [nprapps/elections24-general#333]
See Utah Public Radio page: https://www.upr.org/tags/2024-elections
If you start on Key Races, then click Presidential "County-level results," the embed container doesn't stretch its height enough to show the demographics viz
We need to force the iframe to resize when someone clicks tabs

**Comment by alykat** [comment]
working in this branch: https://github.com/nprapps/elections24-general/tree/333-iframe
