### ISSUE TITLE
Supporting data: Validate 2020 county-level results

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-general#53]
We may be able to just use the file I brought over from the 2022 rig, which reflects 2020 results? [data/prior_fips.csv](https://github.com/nprapps/elections24-general/blob/d362189c88da1e195d82765f7520731a59b48876/data/prior_fips.csv)

Make sure we're using the flag that pulls the [certified results](https://developer.ap.org/ap-elections-api/docs/index.html#t=Elections_Response_Examples.htm&rhsearch=certified&rhhlterm=certified&rhsyns=%20) where available. The [API release notes](https://developer.ap.org/ap-elections-api/docs/index.html#t=Release_Notes.htm&rhsearch=certified&rhhlterm=certified&rhsyns=%20) also say that 2020 and prior certified results are only available in v2 of the API.

The scripts in the `extra` folders may be a starting point for pulling this data:
https://github.com/nprapps/elections24-general/blob/d362189c88da1e195d82765f7520731a59b48876/extras/dump_results.py

We will need to update it to include township-level results if we end up going that direction (#8). And even if we don't, we'll need to re-aggregate township results up to the new county definitions for Connecticut (see #10).

**Comment by abidishajia** [comment]
The data in [data/prior_fips.csv](https://github.com/nprapps/elections24-general/blob/d362189c88da1e195d82765f7520731a59b48876/data/prior_fips.csv) is correct. I added a new file, `get_prior_fips.py` that gets the data.
